[package]
name = "data-backs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39.2", features = ["full"] }
serde = { version= "1.0.204", features= ["derive"] }
serde_json = "1.0.122"
axum = "0.7.5"
# hyper = "1.4.1"
tracing-subscriber = "0.3.18"
chrono = "0.4.38"